version: "3.9"
services:
  #pgdb-dev
  postgresql-dev:
    image: postgres
    container_name: "pgdb-dev"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"