-- =============================================================
-- Script: V1.2.3__create_tb_departamento.sql
-- Descrição: Criação da tabela de departamentos – compatível PG 9+ e H2
-- Autor: Luiz Alberto dos Passos
-- Data: 2025-06-08
-- =============================================================

/* 1 ▸ TABELA --------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS tb_departamento (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               sigla VARCHAR(10)  NOT NULL,
    nome VARCHAR(255) NOT NULL,
    responsavel_id BIGINT,

    CONSTRAINT uk_tb_departamento_sigla UNIQUE (sigla)
    );

/* 2 ▸ DADOS PADRÃO --------------------------------------------------------- */
INSERT INTO tb_departamento (sigla, nome)
SELECT 'CALEM',  'Centro Acadêmico Língua Estrangeira Moderna'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'CALEM');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'DAADM',  'Departamento de Administração'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'DAADM');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'DAGRO',  'Departamento de Agronomia'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'DAGRO');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'DACOC',  'Departamento Acadêmico de Construção Civil'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'DACOC');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'DACON',  'Departamento de Ciências Contábeis'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'DACON');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'DAELE',  'Departamento de Engenharia Elétrica'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'DAELE');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'DAFIS',  'Departamento de Física'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'DAFIS');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'DAHUM',  'Departamento de Ciências Humanas'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'DAHUM');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'DAINF',  'Departamento de Ciência da Computação'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'DAINF');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'DALET',  'Departamento de Letras'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'DALET');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'DAMAT',  'Departamento de Matemática'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'DAMAT');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'DAMEC',  'Departamento de Engenharia Mecânica'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'DAMEC');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'DAQUI',  'Departamento de Química'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'DAQUI');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'LATO_SENSU', 'Departamento de Pós-Graduação Lato Sensu'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'LATO_SENSU');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'STRICTO', 'Departamento de Pós-Graduação Stricto Sensu'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'STRICTO');

INSERT INTO tb_departamento (sigla, nome)
SELECT 'NUAPE',  'Núcleo de Apoio Pedagógico'
    WHERE NOT EXISTS (SELECT 1 FROM tb_departamento WHERE sigla = 'NUAPE');

/* 3 ▸ ÍNDICE --------------------------------------------------------------- */
CREATE INDEX IF NOT EXISTS idx_tb_departamento_responsavel
    ON tb_departamento (responsavel_id);

/* 4 ▸ OBS.: Crie a FK para tb_usuario em migration posterior
   ALTER TABLE tb_departamento
     ADD CONSTRAINT fk_departamento_responsavel
     FOREIGN KEY (responsavel_id) REFERENCES tb_usuario(id);
*/